last patch (maybe)
dodabyte/GradebookSystem pull request #14
Opened 2024-02-28 10:24 UTC by dodabyte

Исправлено:

1) В поля с датой можно было писать любые символы. Теперь же можно только цифры. 2) При редактировании поля dateFormation у объекта теперь автоматически пересчитывается курс и семестр.

Добавлено:

1) Проверка на правильность текущих курсов и семестров при входе суперюзера в систему.

Изменено:

1) TextField groupDateFormationField и studentGroupDateFormationField (дата формирования группы) заменены на DateTextField. 
2) Поля в таблице teacherGroup нельзя редактировать. 
3) В таблице teacherGroup ComboBox teacherDiscipline теперь разделён на два ComboBox: discipline и teacher. ComboBox с объектами teacher заполняется в зависимости от выбранного discipline. 
4) В таблице teacherGroup появилось поле semester. Интерфейс также адаптирован к этому изменению. 
5) Вкладки в стандартном и расширенном режиме претерпели изменения. 
6) Максимальное значение курса и семестра выставляется теперь исходя из имеющихся в БД данных с максимальным значением срока обучения из таблицы specializations.

2024-02-28 13:33 UTC, AtriLux requested changes

2024-02-28 13:33 UTC, AtriLux commented on src/main/java/com/example/lab2/controllers/SuperuserController.java
>          tabPane.getTabs().add(teacherGroupTab);
Назначать преподавателям и специализациям дисциплины и правда нужно редко, обычно все работают по местам. Но назначать преподавателю группы нужно как минимум раз в семестр, т.е. даже чаще, чем добавлять новых студентов. В таком случае возможно стоит перенести этот таб в основные?

2024-02-28 13:33 UTC, AtriLux commented on src/main/java/com/example/lab2/dao/DisciplinesDao.java
> +                            "WHERE t2.lastName = '" + entity.getLastName() +
Зачем искать по всем полям преподавателя в t2, если в t3 есть id, который четко его идентифицирует?

2024-02-28 13:33 UTC, AtriLux commented on src/main/java/com/example/lab2/controllers/SuperuserController.java
> +                new LimitationIntegerConverter(1, AppManager.getSpecializationsDao().findMaxStudyDuration() * 2)));
Получается, теперь при переключении между табами и любыми проверками семестра и курса на валидность отсылается запрос в БД. Возможно лучше кэшировать ответ в AppManager и обновлять при добавлении новых направлений (что случается крайне редко).

2024-02-28 13:33 UTC, AtriLux commented on src/main/sql/db_code.sql
>  							teacher_discipline_id int not null,
Пробелами отступы, пжлст. Чтобы без непонятных прыжков в гитхабе было. Здесь и в других измененных ранее таблицах.

2024-02-28 13:46 UTC, dodabyte commented on src/main/java/com/example/lab2/controllers/SuperuserController.java
> +                new LimitationIntegerConverter(1, AppManager.getSpecializationsDao().findMaxStudyDuration() * 2)));
Это не так работает, в этой строке я инициализирую колонку. Это происходит один раз, при запуске проги.

2024-02-28 13:48 UTC, dodabyte commented on src/main/java/com/example/lab2/dao/DisciplinesDao.java
> +                            "WHERE t2.lastName = '" + entity.getLastName() +
В t3 нет id, который идентифицирует препода. В дисциплинах не хранятся преподаватели. А вот то, что можно было сделать t2.id = entity.getId(), согласен, так и сделаю.

2024-02-28 13:50 UTC, dodabyte commented on src/main/java/com/example/lab2/controllers/SuperuserController.java
>          tabPane.getTabs().add(teacherGroupTab);
Ну, мне кажется, что раз в семестр всё ещё не такая частая ситуация. Разок в семестр суперюзер ткнёт "Расширенный режим", как по мне это не так уж и часто. Хз, мне кажется тут нужно мнение остальных.

2024-02-28 14:20 UTC, AtriLux commented on src/main/java/com/example/lab2/controllers/SuperuserController.java
>          tabPane.getTabs().add(teacherGroupTab);
@Mingogan @LatarichBirka

2024-02-28 14:22 UTC, AtriLux commented on src/main/java/com/example/lab2/controllers/SuperuserController.java
> +                new LimitationIntegerConverter(1, AppManager.getSpecializationsDao().findMaxStudyDuration() * 2)));
Если только при инициализации, то вопрос снимается.

2024-02-28 15:00 UTC, Mingogan commented on src/main/java/com/example/lab2/controllers/SuperuserController.java
>          tabPane.getTabs().add(teacherGroupTab);
Я думаю, что не так часто, поэтому пусть в расширенном лежит

2024-02-29 09:51 UTC, AtriLux approved these changes

2024-02-29 09:51 UTC, merged